##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

---
#######################################
# Master Playbook for the setting up and reseting Hyperledger Bevel DLT network
#######################################
  - hosts: all
    gather_facts: no
    no_log: "{{ no_ansible_log | default(false) }}"
  - import_playbook: network-schema-validator.yaml  
    when: reset is undefined or reset == 'false'       
  - import_playbook: environment-setup.yaml   # First setup environment for each organization
  - import_playbook: kubernetes-env-setup.yaml # Then deploy Flux for each organization
    when: reset is undefined or reset == 'false'  
  - import_playbook: "{{ playbook_dir }}/../../hyperledger-indy/configuration/deploy-network.yaml"
    when: network.type == 'indy' and (reset is undefined or reset == 'false')
    
# Reseting the network
  - import_playbook: "{{ playbook_dir }}/../../hyperledger-indy/configuration/cleanup.yaml"
    when: network.type == 'indy' and reset is defined and reset == 'true'
  
